data:
  # If using opendatasets, e.g. Kaggle dataset URL (requires Kaggle API creds)
  dataset_url: ""
  raw_csv: "data/IMDB Dataset.csv"
  text_column: "review"
  label_column: "sentiment"

  # Artifacts
  tokenizer_path: "models/tokenizer.pkl"
  word2vec_model_path: "models/word2vec.model"
  embedding_matrix_path: "models/embedding_matrix.npy"
  model_path: "models/best_lstm_model.h5"
  history_path: "models/training_history.pkl"
  log_path: "models/training.log"

model:
  max_vocab_size: 20000
  max_sequence_length: 200
  embedding_dim: 300
  lstm_units: 128
  batch_size: 64
  epochs: 8
  validation_split: 0.2
  random_state: 42
